services:
  synapse:
#    image: matrixdotorg/synapse:latest
    image: ghcr.io/element-hq/synapse:latest
    container_name: synapse
    user: "991:991"
    restart: unless-stopped
    ports:
      - "127.0.0.1:8008:8008"  
      - "127.0.0.1:8448:8448"  
    volumes:
      - ./synapse:/data  
    environment:
      - SYNAPSE_CONFIG_DIR=/data
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_SERVER_NAME=ms.aosn.de
      - SYNAPSE_REPORT_STATS=no  
      - SYNAPSE_DB_HOST=db  
      - SYNAPSE_DB_USER=synapse_user  
      - SYNAPSE_DB_NAME=synapse  
      - SYNAPSE_DB_PASSWORD=your_password  
    depends_on:
      - synapse-db  
    networks:
      - matrix_net
    #command: generate

  synapse-db:
    image: postgres:latest
    container_name: synapse-db
    restart: unless-stopped
#    user: "999:999"      #若迁移数据则取消注释
    shm_size: "1g"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U synapse_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse_user
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    volumes:
      - ./synapse_db:/var/lib/postgresql/data:rw 
      - ./synapse_db_conf/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "127.0.0.1:5412:5432"
    networks:
      - matrix_net

##################  worker机 #######################


  generic-worker-1:
    image: matrixdotorg/synapse:latest
    container_name: generic-worker-1
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/generic_worker_1.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8081/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./synapse:/data:rw 
    environment:
      SYNAPSE_WORKER: synapse.app.generic_worker
    ports:
      - 127.0.0.1:9101:9101
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis




  media-worker:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: media-worker
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/media_worker.yaml"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:8083/health || exit 1"]
      start_period: "5s"
      interval: "15s"
      timeout: "5s"
    networks:
      - matrix_net
    volumes:
      - ./synapse:/data:rw
    environment:
      - SYNAPSE_WORKER=synapse.app.media_repository
    ports:
      - 127.0.0.1:9301:9301
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis





  federation-sender-1:
    image: matrixdotorg/synapse:latest
    container_name: federation-sender-1
    restart: unless-stopped
    mem_limit: 1024m
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/federation_sender_1.yaml"]
    healthcheck:
      disable: true
    networks:
      - matrix_net
    volumes:
      - ./synapse:/data:rw 
    ports:
      - 127.0.0.1:9401:9401
    environment:
      SYNAPSE_WORKER: synapse.app.federation_sender
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis


  push-worker:
    image: matrixdotorg/synapse:latest
    user: "991:991"
    container_name: push-worker
    restart: unless-stopped
    entrypoint: ["/start.py", "run", "--config-path=/data/homeserver.yaml", "--config-path=/data/workers/push_worker.yaml"]
    volumes:
      - /root/Matrix/Synapse/synapse:/data:rw
    environment:
      - SYNAPSE_WORKER=synapse.app.pusher
    ports:
      - 9501:9501
    depends_on:
      - synapse
      - synapse-db
      - synapse-redis
    networks:
      - matrix_net


############################## MAS身份验证 ############################


  mas:
    image: ghcr.io/element-hq/matrix-authentication-service:latest
    user: "0:0"
#    image: ghcr.io/element-hq/matrix-authentication-service@sha256:776624188417652362e3f7c6727a9812d0b37ff690a74a3a5c671fe2f3cb82b0
    restart: unless-stopped
    container_name: mas
    ports:
      - 8100:8080
    volumes:
      - ./mas:/data:rw
    networks:
      - matrix_net
    # FIXME: do we also need to sync the db?
    command: "server --config=/data/config.yaml"
    depends_on:
      - mas-db
      - synapse-redis

  mas-db:
    image: postgres:latest
#    user: "999:999"  #若迁移数据则取消注释
    container_name: mas-db
    restart: always
    environment:
      - POSTGRES_DB=mas 
      - POSTGRES_USER=synapse_user  
      - POSTGRES_PASSWORD=your_password  
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    volumes:
      - ./mas_db:/var/lib/postgresql/data  
    ports:
      - "5422:5432"  
    networks:
      - matrix_net
    depends_on:
      - synapse-redis

  synapse-redis:
    image: redis
    restart: unless-stopped
    container_name: synapse-redis
    ports:
      - 127.0.0.1:6378:6379
    networks: 
      - matrix_net



networks:
  matrix_net:
    external: true
